-- PostgreSQL schema (Supabase). Run against the project's Postgres database.

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE admins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TRIGGER trg_admins_updated_at BEFORE UPDATE ON admins
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE cities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT unique_city_name UNIQUE (city_name)
);

CREATE TRIGGER trg_cities_updated_at BEFORE UPDATE ON cities
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE talents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id INTEGER NOT NULL,
    name VARCHAR(180) NOT NULL,
    description TEXT NOT NULL,
    video_url VARCHAR(500) NULL,
    rate VARCHAR(100) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_talents_city FOREIGN KEY (city_id) REFERENCES cities(id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_talents_city_id ON talents(city_id);
CREATE INDEX idx_talents_name ON talents(name);
CREATE INDEX idx_talents_status ON talents(status);

CREATE TRIGGER trg_talents_updated_at BEFORE UPDATE ON talents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE talent_photos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talent_id INTEGER NOT NULL,
    image_url VARCHAR(700) NOT NULL,
    image_display_url VARCHAR(700) NULL,
    image_thumb_url VARCHAR(700) NULL,
    image_medium_url VARCHAR(700) NULL,
    image_delete_url VARCHAR(700) NULL,
    imgbb_id VARCHAR(150) NULL,
    original_filename VARCHAR(255) NULL,
    is_primary SMALLINT NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_talent_photos_talent FOREIGN KEY (talent_id) REFERENCES talents(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_talent_photos_talent_id ON talent_photos(talent_id);
CREATE INDEX idx_talent_photos_is_primary ON talent_photos(is_primary);

-- Called via PostgREST RPC (POST /rest/v1/rpc/set_primary_photo) from PHP so the
-- two-step unset/set stays a single atomic transaction without needing a native
-- Postgres client connection from the app server.
CREATE OR REPLACE FUNCTION set_primary_photo(p_talent_id INTEGER, p_photo_id INTEGER) RETURNS void AS $$
BEGIN
    UPDATE talent_photos SET is_primary = 0 WHERE talent_id = p_talent_id AND deleted_at IS NULL;
    UPDATE talent_photos SET is_primary = 1 WHERE id = p_photo_id AND talent_id = p_talent_id AND deleted_at IS NULL;
END;
$$ LANGUAGE plpgsql;
